import {
  User,
  Trip,
  City,
  Activity,
  Reservation,
  TripDocument,
  ChecklistItem,
  SavedItem,
  NotificationItem,
  TripMember,
} from '../types';

export const INITIAL_USER: User = {
  id: 'user-1',
  name: 'Alex Rivera',
  email: 'alex@globetrotter.io',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
  bio: 'Photographer, cultural explorer & culinary traveler. 24 countries documented.',
  preferredCurrency: 'USD',
  travelStyle: 'Cultural & Adventure',
  createdAt: '2025-01-15T00:00:00.000Z',
};

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    category: 'travel',
    title: 'Upcoming Hotel Check-in',
    message: 'Your Kyoto Machiya Ryokan stay begins in 4 days. Check confirmation details.',
    time: '2h ago',
    unread: true,
    link: '/trips/trip-1',
  },
  {
    id: 'notif-2',
    category: 'planning',
    title: 'Passport Expiration Notice',
    message: 'Your Japanese tourist visa expires in 21 days. Check your Document Wallet.',
    time: '5h ago',
    unread: true,
    link: '/documents',
  },
  {
    id: 'notif-3',
    category: 'budget',
    title: 'Budget Allocation Update',
    message: 'Japan Grand Expedition is at 78% of total budget ($2,180 of $3,500).',
    time: '1d ago',
    unread: false,
    link: '/budget',
  },
  {
    id: 'notif-4',
    category: 'system',
    title: 'Shinkansen Reservation Confirmed',
    message: 'Tokyo to Kyoto Bullet train seats confirmed (Car 4, Seat 8A).',
    time: '2d ago',
    unread: false,
    link: '/reservations',
  },
];

export const INITIAL_MEMBERS: TripMember[] = [
  {
    id: 'mem-1',
    tripId: 'trip-1',
    name: 'Alex Rivera',
    email: 'alex@globetrotter.io',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
    role: 'owner',
    status: 'accepted',
  },
  {
    id: 'mem-2',
    tripId: 'trip-1',
    name: 'Elena Rostova',
    email: 'elena@travel.org',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=150&q=80',
    role: 'editor',
    status: 'accepted',
  },
  {
    id: 'mem-3',
    tripId: 'trip-1',
    name: 'Marcus Chen',
    email: 'marcus@voyage.co',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
    role: 'viewer',
    status: 'accepted',
  },
];

export const INITIAL_RESERVATIONS: Reservation[] = [
  {
    id: 'res-1',
    tripId: 'trip-1',
    type: 'flight',
    provider: 'Japan Airlines (JL 005)',
    title: 'Roundtrip Flight: SFO → NRT (Tokyo)',
    date: '2026-09-03',
    time: '11:45 AM',
    location: 'San Francisco Int Airport (SFO) Terminal I',
    confirmationNumber: 'JL-8849201',
    cost: 1150,
    currency: 'USD',
    status: 'confirmed',
    notes: 'Baggage allowance 2x 23kg included. Seat 22K (Window).',
  },
  {
    id: 'res-2',
    tripId: 'trip-1',
    type: 'hotel',
    provider: 'Hotel Gracery Shinjuku',
    title: 'Shinjuku Deluxe Tower Room (4 Nights)',
    date: '2026-09-03',
    time: '3:00 PM Check-in',
    location: '1-19-1 Kabukicho, Shinjuku, Tokyo',
    confirmationNumber: 'HG-992019',
    cost: 680,
    currency: 'USD',
    status: 'confirmed',
    notes: 'Breakfast included daily. 5 min walk from Shinjuku East Exit.',
  },
  {
    id: 'res-3',
    tripId: 'trip-1',
    type: 'train',
    provider: 'JR Central Shinkansen',
    title: 'Hikari Bullet Train: Tokyo → Kyoto',
    date: '2026-09-07',
    time: '08:33 AM',
    location: 'Tokyo Station Track 14',
    confirmationNumber: 'JR-SHK-4819',
    cost: 135,
    currency: 'USD',
    status: 'confirmed',
    notes: 'Mt. Fuji side seats reserved (Car 5, Seats 8D & 8E).',
  },
  {
    id: 'res-4',
    tripId: 'trip-1',
    type: 'hotel',
    provider: 'Kyoto Machiya Gion Villa',
    title: 'Traditional Wooden Machiya Villa (3 Nights)',
    date: '2026-09-07',
    time: '2:00 PM Check-in',
    location: 'Gion District, Higashiyama, Kyoto',
    confirmationNumber: 'KMG-33019',
    cost: 720,
    currency: 'USD',
    status: 'confirmed',
    notes: 'Tatami rooms with private cypress cedar onsen bath.',
  },
  {
    id: 'res-5',
    tripId: 'trip-1',
    type: 'restaurant',
    provider: 'Sushi Ginza Onodera',
    title: 'Edomae Omakase Chef Table Dinner',
    date: '2026-09-04',
    time: '19:30 PM',
    location: 'Ginza, Chuo City, Tokyo',
    confirmationNumber: 'RES-SGO-102',
    cost: 220,
    currency: 'USD',
    status: 'confirmed',
    notes: 'Smart casual dress code. 18-course seasonal omakase.',
  },
];

export const INITIAL_DOCUMENTS: TripDocument[] = [
  {
    id: 'doc-1',
    tripId: 'trip-1',
    name: 'US Passport (Alex Rivera)',
    type: 'passport',
    documentNumber: 'P772819034',
    issuer: 'US Department of State',
    expirationDate: '2028-11-15',
    status: 'valid',
    notes: 'Valid for 2+ years. 8 blank visa pages remaining.',
  },
  {
    id: 'doc-2',
    tripId: 'trip-1',
    name: 'Japan eVisa Tourist Authorization',
    type: 'visa',
    documentNumber: 'JP-EV-2026-9921',
    issuer: 'Embassy of Japan',
    expirationDate: '2026-09-28',
    status: 'expiring_soon',
    notes: 'Single entry 90-day tourist visa. Print physical copy for border control.',
  },
  {
    id: 'doc-3',
    tripId: 'trip-1',
    name: 'Allianz Global Travel Insurance Policy',
    type: 'insurance',
    documentNumber: 'ALZ-TRV-883910',
    issuer: 'Allianz Care International',
    expirationDate: '2026-09-14',
    status: 'valid',
    notes: '$100,000 medical coverage + baggage delay + flight cancellation.',
  },
  {
    id: 'doc-4',
    tripId: 'trip-1',
    name: 'Japan Airlines E-Ticket Receipt',
    type: 'flight_ticket',
    documentNumber: '131-8849201021',
    issuer: 'Japan Airlines',
    expirationDate: '2026-09-13',
    status: 'valid',
    notes: 'Electronic boarding pass stored in Apple Wallet.',
  },
];

export const INITIAL_CHECKLIST: ChecklistItem[] = [
  { id: 'chk-1', tripId: 'trip-1', title: 'Verify passport validity (min 6 months)', category: 'Documents', isCompleted: true },
  { id: 'chk-2', tripId: 'trip-1', title: 'Apply and download Japan eVisa barcode', category: 'Documents', isCompleted: true },
  { id: 'chk-3', tripId: 'trip-1', title: 'Purchase Ubigi/Airalo Japan eSIM data pack', category: 'Health & Tech', isCompleted: true },
  { id: 'chk-4', tripId: 'trip-1', title: 'Order Japan Rail Whole Pass voucher', category: 'Bookings', isCompleted: true },
  { id: 'chk-5', tripId: 'trip-1', title: 'Notify credit card banks of overseas travel in Japan', category: 'Financial', isCompleted: true },
  { id: 'chk-6', tripId: 'trip-1', title: 'Pack Type-A power outlet adapters & 65W GaN charger', category: 'Health & Tech', isCompleted: false, dueDate: '2026-09-01' },
  { id: 'chk-7', tripId: 'trip-1', title: 'Exchange 30,000 JPY cash for street food markets', category: 'Financial', isCompleted: false, dueDate: '2026-09-02' },
  { id: 'chk-8', tripId: 'trip-1', title: 'Pack slip-on walking shoes for temple visits', category: 'Clothing & Gear', isCompleted: false, dueDate: '2026-09-02' },
  { id: 'chk-9', tripId: 'trip-1', title: 'Confirm pocket Wi-Fi airport pickup counter at Narita', category: 'Bookings', isCompleted: true },
];

export const INITIAL_SAVED_ITEMS: SavedItem[] = [
  {
    id: 'save-1',
    type: 'destination',
    itemId: 'city-2',
    title: 'Tokyo',
    subtitle: 'Japan • Asia',
    image: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=800&q=80',
    category: 'Culture & Modernity',
    cost: 120,
    rating: 4.9,
    collection: 'Japan 2026',
    createdAt: '2026-02-15T10:00:00Z',
  },
  {
    id: 'save-2',
    type: 'activity',
    itemId: 'act-4',
    title: 'TeamLab Planets Immersive Digital Art',
    subtitle: 'Tokyo, Japan',
    image: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=800&q=80',
    category: 'Culture & History',
    cost: 35,
    rating: 4.9,
    collection: 'Japan 2026',
    createdAt: '2026-02-16T12:30:00Z',
  },
  {
    id: 'save-3',
    type: 'destination',
    itemId: 'city-4',
    title: 'Bali',
    subtitle: 'Indonesia • Asia',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=800&q=80',
    category: 'Beach & Relaxation',
    cost: 55,
    rating: 4.8,
    collection: 'Weekend Ideas',
    createdAt: '2026-02-18T09:15:00Z',
  },
  {
    id: 'save-4',
    type: 'activity',
    itemId: 'act-6',
    title: 'Morning Tsukiji Market Sushi Workshop',
    subtitle: 'Tokyo, Japan',
    image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=800&q=80',
    category: 'Food & Dining',
    cost: 65,
    rating: 4.9,
    collection: 'Food Experiences',
    createdAt: '2026-02-20T14:00:00Z',
  },
];

export const INITIAL_CITIES: City[] = [
  {
    id: 'city-1',
    name: 'Jaipur',
    country: 'India',
    region: 'Asia',
    description: 'The Pink City of Rajasthan, famed for majestic forts, royal palaces, vibrant textile bazaars, and opulent heritage.',
    image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80',
    costIndex: 'budget',
    popularityScore: 95,
    averageDailyCost: 45,
    topAttractions: ['Amber Fort', 'Hawa Mahal', 'City Palace', 'Jantar Mantar', 'Nahargarh Fort'],
    climate: 'Semi-arid, warm winters',
    bestTimeToVisit: 'October – March',
    tags: ['Culture', 'Heritage', 'Budget', 'Food'],
    whyVisit: 'Unrivaled royal architecture, vibrant textile craft bazaars, and legendary Rajasthani hospitality.',
    travelTips: ['Hire an official guide at Amber Fort', 'Catch sunset from Nahargarh fort rooftop', 'Carry cash for bazaar shopping'],
    neighborhoods: ['Old Pink City', 'C-Scheme', 'Amer Foothills', 'Civil Lines'],
  },
  {
    id: 'city-2',
    name: 'Tokyo',
    country: 'Japan',
    region: 'Asia',
    description: 'A breathtaking fusion of ultramodern skyline, neon streets, Michelin-starred cuisine, and tranquil Shinto shrines.',
    image: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1200&q=80',
    costIndex: 'moderate',
    popularityScore: 98,
    averageDailyCost: 120,
    topAttractions: ['Shibuya Crossing', 'Senso-ji Temple', 'TeamLab Planets', 'Meiji Jingu', 'Tsukiji Outer Market'],
    climate: 'Temperate, distinct 4 seasons',
    bestTimeToVisit: 'March – May & September – November',
    tags: ['Culture', 'Food', 'Nightlife', 'Modern'],
    whyVisit: 'The world capital of gastronomy, futuristic technology, and deeply serene historical gardens.',
    travelTips: ['Get a Suica transit IC card', 'Book TeamLab 2 weeks in advance', 'Explore Yanaka for vintage Edo atmosphere'],
    neighborhoods: ['Shinjuku', 'Shibuya', 'Ginza', 'Asakusa', 'Roppongi', 'Akihabara'],
  },
  {
    id: 'city-3',
    name: 'Paris',
    country: 'France',
    region: 'Europe',
    description: 'The City of Light known for iconic architecture, world-renowned museums, romantic boulevards, and haute cuisine.',
    image: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=80',
    costIndex: 'luxury',
    popularityScore: 99,
    averageDailyCost: 165,
    topAttractions: ['Eiffel Tower', 'Louvre Museum', 'Notre-Dame', 'Montmartre', 'Sainte-Chapelle'],
    climate: 'Oceanic with mild seasons',
    bestTimeToVisit: 'April – June & September – October',
    tags: ['Culture', 'Food', 'Romantic', 'Luxury'],
    whyVisit: 'Endless masterpieces in the Louvre, cobblestone alleys in Le Marais, and unmatched cafe culture.',
    travelTips: ['Purchase museum passes online', 'Ride the Batobus along the Seine river', 'Picnic by Canal Saint-Martin'],
    neighborhoods: ['Le Marais', 'Montmartre', 'Saint-Germain-des-Prés', 'Latin Quarter'],
  },
  {
    id: 'city-4',
    name: 'Bali',
    country: 'Indonesia',
    region: 'Asia',
    description: 'Tropical paradise of emerald rice terraces, sacred volcanic mountains, vibrant coral reefs, and holistic yoga retreats.',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200&q=80',
    costIndex: 'budget',
    popularityScore: 96,
    averageDailyCost: 55,
    topAttractions: ['Uluwatu Temple', 'Tegallalang Rice Terrace', 'Mount Batur', 'Sacred Monkey Forest', 'Seminyak Beach'],
    climate: 'Tropical warm and humid',
    bestTimeToVisit: 'April – October',
    tags: ['Beach', 'Nature', 'Adventure', 'Relaxation', 'Budget'],
    whyVisit: 'Sun-kissed surf breaks, spiritual water purification temples, and affordable luxury private villas.',
    travelTips: ['Rent a scooter only if experienced', 'Respect local temple dress codes', 'Wake up at 3am for Mount Batur sunrise trek'],
    neighborhoods: ['Ubud', 'Canggu', 'Seminyak', 'Uluwatu', 'Sanur'],
  },
  {
    id: 'city-5',
    name: 'Rome',
    country: 'Italy',
    region: 'Europe',
    description: 'The Eternal City packed with millennia of history, the Colosseum, Vatican treasures, and delicious handmade pasta.',
    image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=1200&q=80',
    costIndex: 'moderate',
    popularityScore: 97,
    averageDailyCost: 135,
    topAttractions: ['Colosseum', 'Vatican Museums', 'Trevi Fountain', 'Pantheon', 'Piazza Navona'],
    climate: 'Mediterranean sunny climate',
    bestTimeToVisit: 'April – May & September – October',
    tags: ['Culture', 'History', 'Food', 'Architecture'],
    whyVisit: 'Walk among ancient imperial ruins by day, and savor cacio e pepe in Trastevere piazza by night.',
    travelTips: ['Carry an empty bottle for free public drinking fountains', 'Book Vatican tickets 1 month prior', 'Wear walking sneakers'],
    neighborhoods: ['Trastevere', 'Centro Storico', 'Monti', 'Prati'],
  },
  {
    id: 'city-6',
    name: 'Santorini',
    country: 'Greece',
    region: 'Europe',
    description: 'Iconic whitewashed caldera cliffside villages, cobalt blue dome churches, and legendary Aegean sea sunsets.',
    image: 'https://images.unsplash.com/photo-1570077188670-e3a8d69ac5ff?auto=format&fit=crop&w=1200&q=80',
    costIndex: 'luxury',
    popularityScore: 96,
    averageDailyCost: 185,
    topAttractions: ['Oia Sunset Point', 'Fira to Oia Cliff Hike', 'Red Beach', 'Amoudi Bay', 'Akrotiri Ruins'],
    climate: 'Mediterranean dry sunny summers',
    bestTimeToVisit: 'May – June & September – October',
    tags: ['Beach', 'Relaxation', 'Romantic', 'Luxury'],
    whyVisit: 'Sip volcanic Assyrtiko wine overlooking a sunken volcanic caldera as the sun melts into the Aegean.',
    travelTips: ['Hike from Fira to Oia in the morning', 'Book a catamaran sunset cruise with BBQ', 'Wear flat shoes for stairs'],
    neighborhoods: ['Oia', 'Fira', 'Imerovigli', 'Amoudi Bay'],
  },
];

export const INITIAL_ACTIVITIES: Activity[] = [
  {
    id: 'act-1',
    cityId: 'city-1',
    cityName: 'Jaipur',
    name: 'Sunrise Amber Fort & Sheesh Mahal Tour',
    category: 'Sightseeing',
    cost: 15,
    durationMinutes: 180,
    description: 'Explore the grand 16th-century fortress, Sheesh Mahal (Palace of Mirrors), and panoramic valley vistas.',
    image: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=600&q=80',
    rating: 4.9,
    location: 'Devisinghpura, Amer, Jaipur',
  },
  {
    id: 'act-2',
    cityId: 'city-1',
    cityName: 'Jaipur',
    name: 'Old City Rajasthani Street Food Safari',
    category: 'Food & Dining',
    cost: 25,
    durationMinutes: 120,
    description: 'Taste authentic pyaz kachoris, ghewar sweets, and spiced masala chai in bustling Johari Bazaar.',
    image: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?auto=format&fit=crop&w=600&q=80',
    rating: 4.8,
    location: 'Johari Bazaar, Old City',
  },
  {
    id: 'act-4',
    cityId: 'city-2',
    cityName: 'Tokyo',
    name: 'TeamLab Planets Immersive Digital Art',
    category: 'Culture & History',
    cost: 35,
    durationMinutes: 120,
    description: 'Walk through water and body-immersive digital light exhibits that blur the boundaries between art and self.',
    image: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=600&q=80',
    rating: 4.9,
    location: 'Toyosu, Koto City, Tokyo',
  },
  {
    id: 'act-5',
    cityId: 'city-2',
    cityName: 'Tokyo',
    name: 'Shibuya Crossing & Omoide Yokocho Izakaya',
    category: 'Nightlife',
    cost: 40,
    durationMinutes: 180,
    description: 'Cross the world’s busiest pedestrian crossing and feast on yakitori skewers in atmospheric neon-lit alleyways.',
    image: 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?auto=format&fit=crop&w=600&q=80',
    rating: 4.8,
    location: 'Shibuya & Shinjuku, Tokyo',
  },
  {
    id: 'act-6',
    cityId: 'city-2',
    cityName: 'Tokyo',
    name: 'Morning Tsukiji Market Sushi Workshop',
    category: 'Food & Dining',
    cost: 65,
    durationMinutes: 150,
    description: 'Learn sushi rolling techniques from master chefs with fresh catch straight from Toyosu fish auctions.',
    image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=600&q=80',
    rating: 4.9,
    location: 'Tsukiji, Chuo City, Tokyo',
  },
  {
    id: 'act-9',
    cityId: 'city-4',
    cityName: 'Bali',
    name: 'Mount Batur Sunrise Volcano Trek',
    category: 'Adventure',
    cost: 45,
    durationMinutes: 300,
    description: 'Hike before dawn to witness a breathtaking sunrise above the clouds and volcanic crater lake.',
    image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=600&q=80',
    rating: 4.9,
    location: 'Kintamani, Bali',
  },
];

export const INITIAL_TRIPS: Trip[] = [
  {
    id: 'trip-1',
    userId: 'user-1',
    title: 'Japan Grand Expedition',
    description: 'A 10-day cultural voyage through Tokyo neon alleys, Kyoto bamboo groves, and Osaka culinary markets.',
    startDate: '2026-09-03',
    endDate: '2026-09-13',
    coverImage: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1200&q=80',
    budget: 3500,
    status: 'planned',
    destinationSummary: 'Tokyo → Kyoto → Osaka',
    shareId: 'share-japan-2026',
    isPublic: true,
    createdAt: '2026-02-10T10:00:00Z',
    members: INITIAL_MEMBERS,
    reservations: INITIAL_RESERVATIONS,
    documents: INITIAL_DOCUMENTS,
    checklist: INITIAL_CHECKLIST,
    stops: [
      {
        id: 'stop-1',
        tripId: 'trip-1',
        cityId: 'city-2',
        cityName: 'Tokyo',
        country: 'Japan',
        arrivalDate: '2026-09-03',
        departureDate: '2026-09-07',
        order: 1,
        notes: 'Stay near Shinjuku Station for convenient JR Yamanote Line connectivity.',
        coverImage: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=800&q=80',
        activities: [
          {
            id: 'ta-1',
            stopId: 'stop-1',
            activityId: 'act-4',
            name: 'TeamLab Planets Immersive Digital Art',
            category: 'Culture & History',
            dayNumber: 1,
            date: '2026-09-03',
            startTime: '14:00',
            endTime: '16:30',
            cost: 35,
            notes: 'Barefoot digital art experience. Tickets pre-booked for 2:00 PM slot.',
            location: 'Toyosu, Tokyo',
            isCompleted: true,
          },
          {
            id: 'ta-2',
            stopId: 'stop-1',
            activityId: 'act-5',
            name: 'Shibuya Crossing & Omoide Yokocho Izakaya',
            category: 'Nightlife',
            dayNumber: 1,
            date: '2026-09-03',
            startTime: '18:30',
            endTime: '21:00',
            cost: 40,
            notes: 'Cross the world’s busiest pedestrian intersection and enjoy yakitori in Shinjuku.',
            location: 'Shibuya & Shinjuku',
            isCompleted: true,
          },
          {
            id: 'ta-3',
            stopId: 'stop-1',
            activityId: 'act-6',
            name: 'Morning Tsukiji Market Sushi Workshop',
            category: 'Food & Dining',
            dayNumber: 2,
            date: '2026-09-04',
            startTime: '08:30',
            endTime: '11:00',
            cost: 65,
            notes: 'Meet chef at entrance. Bring appetite for fresh otoro tuna.',
            location: 'Tsukiji Outer Market',
            isCompleted: false,
          },
        ],
      },
      {
        id: 'stop-2',
        tripId: 'trip-1',
        cityName: 'Kyoto',
        country: 'Japan',
        arrivalDate: '2026-09-07',
        departureDate: '2026-09-10',
        order: 2,
        notes: 'Take early Shinkansen Hikari bullet train from Tokyo Station.',
        coverImage: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=800&q=80',
        activities: [
          {
            id: 'ta-4',
            stopId: 'stop-2',
            name: 'Fushimi Inari 10,000 Torii Gates Morning Hike',
            category: 'Culture & History',
            dayNumber: 5,
            date: '2026-09-07',
            startTime: '07:00',
            endTime: '09:30',
            cost: 0,
            notes: 'Hike to the summit before crowds arrive.',
            location: 'Fushimi Ward, Kyoto',
            isCompleted: false,
          },
          {
            id: 'ta-5',
            stopId: 'stop-2',
            name: 'Arashiyama Bamboo Grove & Tenryu-ji Temple',
            category: 'Nature',
            dayNumber: 6,
            date: '2026-09-08',
            startTime: '09:00',
            endTime: '12:00',
            cost: 10,
            notes: 'UNESCO World Heritage Zen garden.',
            location: 'Arashiyama, Kyoto',
            isCompleted: false,
          },
        ],
      },
      {
        id: 'stop-3',
        tripId: 'trip-1',
        cityName: 'Osaka',
        country: 'Japan',
        arrivalDate: '2026-09-10',
        departureDate: '2026-09-13',
        order: 3,
        notes: 'Stay in Namba near Dotonbori neon canal.',
        coverImage: 'https://images.unsplash.com/photo-1590253230537-8f522f77894d?auto=format&fit=crop&w=800&q=80',
        activities: [
          {
            id: 'ta-6',
            stopId: 'stop-3',
            name: 'Dotonbori Street Food Feast & Glico Sign',
            category: 'Food & Dining',
            dayNumber: 8,
            date: '2026-09-10',
            startTime: '18:00',
            endTime: '21:00',
            cost: 35,
            notes: 'Try piping hot takoyaki and okonomiyaki.',
            location: 'Dotonbori, Osaka',
            isCompleted: false,
          },
        ],
      },
    ],
    expenses: [
      {
        id: 'exp-1',
        tripId: 'trip-1',
        title: '7-Day Whole Japan Rail Pass (Green Car)',
        category: 'transport',
        amount: 380,
        currency: 'USD',
        date: '2026-09-03',
        notes: 'Pre-activated at Haneda Airport',
      },
      {
        id: 'exp-2',
        tripId: 'trip-1',
        title: 'Shinjuku Boutique Hotel (4 nights)',
        category: 'accommodation',
        amount: 680,
        currency: 'USD',
        date: '2026-09-03',
      },
      {
        id: 'exp-3',
        tripId: 'trip-1',
        title: 'Traditional Kyoto Machiya Ryokan (3 nights)',
        category: 'accommodation',
        amount: 720,
        currency: 'USD',
        date: '2026-09-07',
      },
      {
        id: 'exp-4',
        tripId: 'trip-1',
        title: 'Omakase Dinner at Ginza Sushi Ichi',
        category: 'food',
        amount: 220,
        currency: 'USD',
        date: '2026-09-04',
      },
      {
        id: 'exp-5',
        tripId: 'trip-1',
        title: 'Handmade Kyoto Ceramic Tea Set',
        category: 'shopping',
        amount: 180,
        currency: 'USD',
        date: '2026-09-08',
      },
    ],
  },
  {
    id: 'trip-2',
    userId: 'user-1',
    title: 'Rajasthan Royal Heritage Trail',
    description: 'A 6-day expedition traversing royal forts, palace heritage, spicy culinary treats, and desert sunsets.',
    startDate: '2026-10-15',
    endDate: '2026-10-21',
    coverImage: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1200&q=80',
    budget: 1500,
    status: 'planned',
    destinationSummary: 'Jaipur → Jodhpur → Udaipur',
    shareId: 'share-raj-2026',
    isPublic: true,
    createdAt: '2026-01-20T14:30:00Z',
    stops: [
      {
        id: 'stop-10',
        tripId: 'trip-2',
        cityId: 'city-1',
        cityName: 'Jaipur',
        country: 'India',
        arrivalDate: '2026-10-15',
        departureDate: '2026-10-18',
        order: 1,
        notes: 'Stay at heritage haveli near Hawa Mahal.',
        coverImage: 'https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80',
        activities: [
          {
            id: 'ta-10',
            stopId: 'stop-10',
            activityId: 'act-1',
            name: 'Sunrise Amber Fort & Sheesh Mahal Tour',
            category: 'Sightseeing',
            dayNumber: 1,
            date: '2026-10-15',
            startTime: '07:00',
            endTime: '10:00',
            cost: 15,
            isCompleted: false,
          },
        ],
      },
    ],
    expenses: [
      {
        id: 'exp-10',
        tripId: 'trip-2',
        title: 'Heritage Haveli Hotel Jaipur',
        category: 'accommodation',
        amount: 280,
        currency: 'USD',
        date: '2026-10-15',
      },
      {
        id: 'exp-11',
        tripId: 'trip-2',
        title: 'Private Chauffeur Car across Rajasthan',
        category: 'transport',
        amount: 220,
        currency: 'USD',
        date: '2026-10-15',
      },
    ],
  },
  {
    id: 'trip-3',
    userId: 'user-1',
    title: 'Parisian Spring Romance & Art',
    description: 'Museum hopping, Seine river cruises, French bakeries, and day trips to Versailles Palace.',
    startDate: '2025-05-01',
    endDate: '2025-05-08',
    coverImage: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1200&q=80',
    budget: 2500,
    status: 'completed',
    destinationSummary: 'Paris, Versailles',
    shareId: 'share-paris-2025',
    isPublic: true,
    createdAt: '2025-03-01T09:00:00Z',
    stops: [],
    expenses: [
      {
        id: 'exp-20',
        tripId: 'trip-3',
        title: 'Charming Marais Loft',
        category: 'accommodation',
        amount: 1100,
        currency: 'USD',
        date: '2025-05-01',
      },
    ],
  },
];
